acme_rest_api_currencies_all:
    pattern:  /currency/all
    defaults: { _controller: AcmeExchangeRateBundle:Currency:getAll, _format: ~ }
    requirements:
        _method: GET

acme_rest_api_currency_get:
    pattern:  /currency/{id}
    defaults: { _controller: AcmeExchangeRateBundle:Currency:get, _format: ~ }
    requirements:
        _method: GET
        id: "\d+"

acme_rest_api_exchange_rate_get:
    pattern:  /exchange_rate/{code}
    defaults: { _controller: AcmeExchangeRateBundle:ExchangeRate:get, _format: ~ }
    requirements:
        _method: GET
        code: "\w+"